### ISSUE TITLE
Log - Runtime error

### ISSUE THREAD

**Issue by linhtlthp** [mjnaderi/Sharif-Judge#23] opened 2015-03-12 09:26 UTC
![screenshot 72](https://cloud.githubusercontent.com/assets/11305086/6615226/900928ba-c8d4-11e4-8980-e81f26a108b2.png)

**Comment by mjnaderi** [comment] 2015-03-12 16:21
Duplicate of #21. Closed.

**Closed as completed by mjnaderi** 2015-03-12 16:21 UTC
Labels: duplicate
